---

# ansible-galaxy role install -r requirements.yml -p ./roles
roles:

  - name: robertdebock.bootstrap
    version: 4.3.6

  - name: robertdebock.core_dependencies
    version: 1.5.3

  - name: MichaelRigart.interfaces
    version: v1.9.0

  - name: geerlingguy.firewall
    version: 2.5.0

  - name: robertdebock.cron
    version: 1.7.3

  - name: robertdebock.ntp
    version: 2.7.5

  - name: robertdebock.postfix
    version: 3.3.7

  - name: willshersystems.sshd
    version: v0.12.0

  - name: robertdebock.fail2ban
    version: 3.1.9

  - name: robertdebock.users
    version: 4.4.1

  - name: robertdebock.rsyslog
    version: 3.1.0

  - name: geerlingguy.postgresql
    version: 3.0.0

  - name: pescobar.apache_tomcat
    version: 2.3.0

  # - name: nvidia.nvidia_driver
  #   src: https://github.com/pescobar/ansible-role-nvidia-driver.git
  #   scm: git
  #   version: add_repos_optional


# ansible-galaxy collection install -r requirements.yml -p ./collections
# collections:

#   - name: theforeman.foreman
#     version: 0.8.0
